blank_issues_enabled: false
issue_templates:
  - name: 舉誤與建議
    description: 提出勘誤、補充或建議。
    title: "【舉誤建議】"
    labels: ["suggestion"]
    file: suggestions.md
  - name: 請益與討論
    description: 提出疑義或研討。
    title: "【請益討論】"
    labels: ["discussion"]
    file: discussion.md
